INSERT INTO products (title, description, price_cents, image) VALUES
('Poster: Misty Forest (18×24 in)', 'Premium matte poster • 18×24 in. Printed on archival 200gsm paper. Ready to frame.', 4545, 'https://picsum.photos/seed/misty-forest/800/1000'),
('Poster: Golden Dunes (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 4508, 'https://picsum.photos/seed/golden-dunes/800/1000'),
('Poster: Neon Cityscape (18×24 in)', 'Premium matte poster • 18×24 in. Printed on archival 200gsm paper. Ready to frame.', 2849, 'https://picsum.photos/seed/neon-cityscape/800/1000'),
('Poster: Snowy Peaks (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 4501, 'https://picsum.photos/seed/snowy-peaks/800/1000'),
('Poster: Sunset Boulevard (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 1776, 'https://picsum.photos/seed/sunset-boulevard/800/1000'),
('Poster: Vintage Surf Van (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 4291, 'https://picsum.photos/seed/vintage-surf-van/800/1000'),
('Poster: Desert Highway (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 2947, 'https://picsum.photos/seed/desert-highway/800/1000'),
('Poster: Lavender Fields (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 3513, 'https://picsum.photos/seed/lavender-fields/800/1000'),
('Poster: Midnight Ocean (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 1384, 'https://picsum.photos/seed/midnight-ocean/800/1000'),
('Poster: Autumn Trail (18×24 in)', 'Premium matte poster • 18×24 in. Printed on archival 200gsm paper. Ready to frame.', 2241, 'https://picsum.photos/seed/autumn-trail/800/1000'),
('Poster: Cherry Blossoms (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 1370, 'https://picsum.photos/seed/cherry-blossoms/800/1000'),
('Poster: Monstera Leaves (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 4315, 'https://picsum.photos/seed/monstera-leaves/800/1000'),
('Poster: Abstract Geometry (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 3597, 'https://picsum.photos/seed/abstract-geometry/800/1000'),
('Poster: Retro Cassette (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 3437, 'https://picsum.photos/seed/retro-cassette/800/1000'),
('Poster: Paper Cranes (18×24 in)', 'Premium matte poster • 18×24 in. Printed on archival 200gsm paper. Ready to frame.', 4950, 'https://picsum.photos/seed/paper-cranes/800/1000'),
('Poster: Starry Night Sky (18×24 in)', 'Premium matte poster • 18×24 in. Printed on archival 200gsm paper. Ready to frame.', 3677, 'https://picsum.photos/seed/starry-night-sky/800/1000'),
('Poster: Coastal Lighthouse (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 3520, 'https://picsum.photos/seed/coastal-lighthouse/800/1000'),
('Poster: Foggy Harbor (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 1644, 'https://picsum.photos/seed/foggy-harbor/800/1000'),
('Poster: Citrus Still Life (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 1060, 'https://picsum.photos/seed/citrus-still-life/800/1000'),
('Poster: Map of Paris (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 1257, 'https://picsum.photos/seed/map-of-paris/800/1000'),
('Poster: Minimalist Mountains (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 1145, 'https://picsum.photos/seed/minimalist-mountains/800/1000'),
('Poster: Cosmic Nebula (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 4601, 'https://picsum.photos/seed/cosmic-nebula/800/1000'),
('Poster: Rainy Window (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 3455, 'https://picsum.photos/seed/rainy-window/800/1000'),
('Poster: Black Cat Silhouette (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 4186, 'https://picsum.photos/seed/black-cat-silhouette/800/1000'),
('Poster: Ginkgo Pattern (18×24 in)', 'Premium matte poster • 18×24 in. Printed on archival 200gsm paper. Ready to frame.', 2335, 'https://picsum.photos/seed/ginkgo-pattern/800/1000'),
('Poster: Palm Shadows (18×24 in)', 'Premium matte poster • 18×24 in. Printed on archival 200gsm paper. Ready to frame.', 3419, 'https://picsum.photos/seed/palm-shadows/800/1000'),
('Poster: Retro Arcade (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 3125, 'https://picsum.photos/seed/retro-arcade/800/1000'),
('Poster: Pastel Clouds (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 3621, 'https://picsum.photos/seed/pastel-clouds/800/1000'),
('Poster: Wildflowers Meadow (18×24 in)', 'Premium matte poster • 18×24 in. Printed on archival 200gsm paper. Ready to frame.', 3046, 'https://picsum.photos/seed/wildflowers-meadow/800/1000'),
('Poster: Zen Stones (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 3712, 'https://picsum.photos/seed/zen-stones/800/1000'),
('Poster: Moon Phases (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 2872, 'https://picsum.photos/seed/moon-phases/800/1000'),
('Poster: City Bike Lane (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 2138, 'https://picsum.photos/seed/city-bike-lane/800/1000'),
('Poster: Blue Hour Canal (18×24 in)', 'Premium matte poster • 18×24 in. Printed on archival 200gsm paper. Ready to frame.', 3256, 'https://picsum.photos/seed/blue-hour-canal/800/1000'),
('Poster: Grainy Film Street (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 3898, 'https://picsum.photos/seed/grainy-film-street/800/1000'),
('Poster: Seagulls in Flight (18×24 in)', 'Premium matte poster • 18×24 in. Printed on archival 200gsm paper. Ready to frame.', 2290, 'https://picsum.photos/seed/seagulls-in-flight/800/1000'),
('Poster: Firewatch Lookout (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 3099, 'https://picsum.photos/seed/firewatch-lookout/800/1000'),
('Poster: Northern Lights (18×24 in)', 'Premium matte poster • 18×24 in. Printed on archival 200gsm paper. Ready to frame.', 1120, 'https://picsum.photos/seed/northern-lights/800/1000'),
('Poster: Sakura Alley (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 3305, 'https://picsum.photos/seed/sakura-alley/800/1000'),
('Poster: Grunge Brick Wall (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 2639, 'https://picsum.photos/seed/grunge-brick-wall/800/1000'),
('Poster: Café Terrace (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 4466, 'https://picsum.photos/seed/caf-terrace/800/1000'),
('Poster: Old Library (18×24 in)', 'Premium matte poster • 18×24 in. Printed on archival 200gsm paper. Ready to frame.', 2582, 'https://picsum.photos/seed/old-library/800/1000'),
('Poster: Typewriter Keys (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 4923, 'https://picsum.photos/seed/typewriter-keys/800/1000'),
('Poster: Vinyl Record (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 4469, 'https://picsum.photos/seed/vinyl-record/800/1000'),
('Poster: Tropical Waterfall (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 1001, 'https://picsum.photos/seed/tropical-waterfall/800/1000'),
('Poster: Bamboo Grove (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 1858, 'https://picsum.photos/seed/bamboo-grove/800/1000'),
('Poster: Industrial Bridge (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 2924, 'https://picsum.photos/seed/industrial-bridge/800/1000'),
('Poster: Streetcar Tracks (18×24 in)', 'Premium matte poster • 18×24 in. Printed on archival 200gsm paper. Ready to frame.', 3902, 'https://picsum.photos/seed/streetcar-tracks/800/1000'),
('Poster: Snowy Forest Road (18×24 in)', 'Premium matte poster • 18×24 in. Printed on archival 200gsm paper. Ready to frame.', 2718, 'https://picsum.photos/seed/snowy-forest-road/800/1000'),
('Poster: Butterfly Macro (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 3318, 'https://picsum.photos/seed/butterfly-macro/800/1000'),
('Poster: Koi Pond (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 1812, 'https://picsum.photos/seed/koi-pond/800/1000'),
('Poster: Morning Fog Hills (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 2104, 'https://picsum.photos/seed/morning-fog-hills/800/1000'),
('Poster: Cathedral Facade (18×24 in)', 'Premium matte poster • 18×24 in. Printed on archival 200gsm paper. Ready to frame.', 1355, 'https://picsum.photos/seed/cathedral-facade/800/1000'),
('Poster: Pinecone Closeup (18×24 in)', 'Premium matte poster • 18×24 in. Printed on archival 200gsm paper. Ready to frame.', 2361, 'https://picsum.photos/seed/pinecone-closeup/800/1000'),
('Poster: Wild Coast (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 4947, 'https://picsum.photos/seed/wild-coast/800/1000'),
('Poster: Glasshouse Palms (18×24 in)', 'Premium matte poster • 18×24 in. Printed on archival 200gsm paper. Ready to frame.', 4103, 'https://picsum.photos/seed/glasshouse-palms/800/1000'),
('Poster: Sunlit Alley (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 1550, 'https://picsum.photos/seed/sunlit-alley/800/1000'),
('Poster: Golden Gate Vista (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 3894, 'https://picsum.photos/seed/golden-gate-vista/800/1000'),
('Poster: Harbor Boats (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 1043, 'https://picsum.photos/seed/harbor-boats/800/1000'),
('Poster: Candy Shop (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 2903, 'https://picsum.photos/seed/candy-shop/800/1000'),
('Poster: Lemon Pattern (18×24 in)', 'Premium matte poster • 18×24 in. Printed on archival 200gsm paper. Ready to frame.', 1726, 'https://picsum.photos/seed/lemon-pattern/800/1000'),
('Poster: Cobalt Waves (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 3289, 'https://picsum.photos/seed/cobalt-waves/800/1000'),
('Poster: Pepper Sketch (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 2831, 'https://picsum.photos/seed/pepper-sketch/800/1000'),
('Poster: Ferns Study (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 1780, 'https://picsum.photos/seed/ferns-study/800/1000'),
('Poster: Iridescent Bubbles (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 4150, 'https://picsum.photos/seed/iridescent-bubbles/800/1000'),
('Poster: Paper Cut Shapes (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 2716, 'https://picsum.photos/seed/paper-cut-shapes/800/1000'),
('Poster: Vintage Camera (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 2570, 'https://picsum.photos/seed/vintage-camera/800/1000'),
('Poster: Old Map Sketch (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 2616, 'https://picsum.photos/seed/old-map-sketch/800/1000'),
('Poster: Guitar Headstock (18×24 in)', 'Premium matte poster • 18×24 in. Printed on archival 200gsm paper. Ready to frame.', 1870, 'https://picsum.photos/seed/guitar-headstock/800/1000'),
('Poster: Vinyl Player (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 2104, 'https://picsum.photos/seed/vinyl-player/800/1000'),
('Poster: Chess Endgame (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 2244, 'https://picsum.photos/seed/chess-endgame/800/1000'),
('Poster: Hot Air Balloons (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 1862, 'https://picsum.photos/seed/hot-air-balloons/800/1000'),
('Poster: Canal Bridge (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 2613, 'https://picsum.photos/seed/canal-bridge/800/1000'),
('Poster: Rainforest Canopy (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 3627, 'https://picsum.photos/seed/rainforest-canopy/800/1000'),
('Poster: Rocky Shore (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 1409, 'https://picsum.photos/seed/rocky-shore/800/1000'),
('Poster: City Reflections (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 1598, 'https://picsum.photos/seed/city-reflections/800/1000'),
('Poster: Geometric Sunset (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 2807, 'https://picsum.photos/seed/geometric-sunset/800/1000'),
('Poster: Desert Cactus (18×24 in)', 'Premium matte poster • 18×24 in. Printed on archival 200gsm paper. Ready to frame.', 1038, 'https://picsum.photos/seed/desert-cactus/800/1000'),
('Poster: Marble Texture (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 2346, 'https://picsum.photos/seed/marble-texture/800/1000'),
('Poster: Terracotta Pots (18×24 in)', 'Premium matte poster • 18×24 in. Printed on archival 200gsm paper. Ready to frame.', 2580, 'https://picsum.photos/seed/terracotta-pots/800/1000'),
('Poster: Desert Night (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 1303, 'https://picsum.photos/seed/desert-night/800/1000'),
('Poster: Railway Station (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 1853, 'https://picsum.photos/seed/railway-station/800/1000'),
('Poster: Color Blocks (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 3606, 'https://picsum.photos/seed/color-blocks/800/1000'),
('Poster: Ocean Cliff (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 1062, 'https://picsum.photos/seed/ocean-cliff/800/1000'),
('Poster: Stepping Stones (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 2509, 'https://picsum.photos/seed/stepping-stones/800/1000'),
('Poster: Sandy Cove (18×24 in)', 'Premium matte poster • 18×24 in. Printed on archival 200gsm paper. Ready to frame.', 3547, 'https://picsum.photos/seed/sandy-cove/800/1000'),
('Poster: Blue Hydrangeas (18×24 in)', 'Premium matte poster • 18×24 in. Printed on archival 200gsm paper. Ready to frame.', 1520, 'https://picsum.photos/seed/blue-hydrangeas/800/1000'),
('Poster: Fjord Vista (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 2980, 'https://picsum.photos/seed/fjord-vista/800/1000'),
('Poster: Steel Staircase (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 1554, 'https://picsum.photos/seed/steel-staircase/800/1000'),
('Poster: Crimson Leaves (18×24 in)', 'Premium matte poster • 18×24 in. Printed on archival 200gsm paper. Ready to frame.', 1747, 'https://picsum.photos/seed/crimson-leaves/800/1000'),
('Poster: Riverside Walk (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 1630, 'https://picsum.photos/seed/riverside-walk/800/1000'),
('Poster: Tea Ceremony (18×24 in)', 'Premium matte poster • 18×24 in. Printed on archival 200gsm paper. Ready to frame.', 4719, 'https://picsum.photos/seed/tea-ceremony/800/1000'),
('Poster: Paper Boats (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 4348, 'https://picsum.photos/seed/paper-boats/800/1000'),
('Poster: Morning Commute (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 2020, 'https://picsum.photos/seed/morning-commute/800/1000'),
('Poster: City Rooftops (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 1776, 'https://picsum.photos/seed/city-rooftops/800/1000'),
('Poster: Old Book Spines (12×16 in)', 'Premium matte poster • 12×16 in. Printed on archival 200gsm paper. Ready to frame.', 4027, 'https://picsum.photos/seed/old-book-spines/800/1000'),
('Poster: Tulip Field (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 4850, 'https://picsum.photos/seed/tulip-field/800/1000'),
('Poster: Lavender Sunset (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 1804, 'https://picsum.photos/seed/lavender-sunset/800/1000'),
('Poster: Thunderstorm Sky (24×36 in)', 'Premium matte poster • 24×36 in. Printed on archival 200gsm paper. Ready to frame.', 4890, 'https://picsum.photos/seed/thunderstorm-sky/800/1000'),
('Poster: Forest Stream (18×24 in)', 'Premium matte poster • 18×24 in. Printed on archival 200gsm paper. Ready to frame.', 4612, 'https://picsum.photos/seed/forest-stream/800/1000'),
('Poster: Art Deco Facade (18×24 in)', 'Premium matte poster • 18×24 in. Printed on archival 200gsm paper. Ready to frame.', 3471, 'https://picsum.photos/seed/art-deco-facade/800/1000');
INSERT INTO reviews (product_id, author, body, rating) VALUES
(1, 'Maria', 'Beautiful print and great quality.', 4),
(1, 'Maria', 'Wish it came with a frame.', 1),
(2, 'Liam', 'Wish it came with a frame.', 2),
(2, 'Elena', 'Arrived quickly and well-packaged.', 4),
(2, 'Liu', 'Exactly as pictured; love it!', 5),
(2, 'Akira', 'Beautiful print and great quality.', 5),
(3, 'Liu', 'Wish it came with a frame.', 2),
(3, 'Mateo', 'Beautiful print and great quality.', 5),
(3, 'Sofia', 'Good quality for the price.', 3),
(4, 'Elena', 'Paper had a minor crease.', 1),
(4, 'Sofia', 'Beautiful print and great quality.', 4),
(5, 'Elena', 'Paper had a minor crease.', 2),
(5, 'Mateo', 'Colors are vibrant; looks fantastic framed.', 5),
(6, 'Akira', 'Looks nice; size is accurate.', 3),
(6, 'Priya', 'Satisfied with the purchase.', 3),
(7, 'Maria', 'Beautiful print and great quality.', 5),
(7, 'Olivia', 'Exactly as pictured; love it!', 4),
(7, 'Maria', 'Good quality for the price.', 3),
(8, 'John', 'Exactly as pictured; love it!', 4),
(8, 'Akira', 'Good quality for the price.', 3),
(9, 'Ava', 'Exactly as pictured; love it!', 4),
(9, 'Olivia', 'Wish it came with a frame.', 1),
(10, 'Hassan', 'Good quality for the price.', 3),
(10, 'Olivia', 'Beautiful print and great quality.', 4),
(10, 'Emma', 'Beautiful print and great quality.', 4),
(11, 'Maria', 'Adds style to my living room.', 5),
(11, 'Noah', 'Adds style to my living room.', 4),
(11, 'Mateo', 'Colors slightly darker than expected.', 1),
(11, 'John', 'Wish it came with a frame.', 1),
(11, 'Elena', 'Paper had a minor crease.', 1),
(12, 'Olivia', 'Adds style to my living room.', 4),
(12, 'Liu', 'Arrived quickly and well-packaged.', 4),
(12, 'John', 'Adds style to my living room.', 5),
(12, 'Maria', 'Exactly as pictured; love it!', 5),
(13, 'Maria', 'Colors are vibrant; looks fantastic framed.', 4),
(13, 'Liu', 'Wish it came with a frame.', 1),
(14, 'Olivia', 'Good quality for the price.', 3),
(14, 'Elena', 'Good quality for the price.', 3),
(14, 'Sofia', 'Adds style to my living room.', 5),
(14, 'Emma', 'Paper had a minor crease.', 2),
(14, 'Liu', 'Colors are vibrant; looks fantastic framed.', 4),
(15, 'Priya', 'Exactly as pictured; love it!', 4),
(15, 'Priya', 'Paper had a minor crease.', 2),
(15, 'Olivia', 'Colors slightly darker than expected.', 2),
(15, 'Sofia', 'Adds style to my living room.', 4),
(16, 'Akira', 'Colors slightly darker than expected.', 2),
(16, 'Hassan', 'Beautiful print and great quality.', 4),
(16, 'Elena', 'Colors slightly darker than expected.', 1),
(16, 'Liu', 'Paper had a minor crease.', 1),
(17, 'Lucas', 'Paper had a minor crease.', 2),
(17, 'Priya', 'Adds style to my living room.', 4),
(17, 'Priya', 'Exactly as pictured; love it!', 4),
(17, 'Liu', 'Exactly as pictured; love it!', 5),
(18, 'Elena', 'Wish it came with a frame.', 1),
(18, 'Priya', 'Wish it came with a frame.', 1),
(19, 'Hassan', 'Exactly as pictured; love it!', 5),
(19, 'Maria', 'Colors are vibrant; looks fantastic framed.', 5),
(19, 'Liu', 'Colors are vibrant; looks fantastic framed.', 4),
(19, 'Emma', 'Paper had a minor crease.', 1),
(20, 'Emma', 'Colors slightly darker than expected.', 2),
(20, 'Liu', 'Colors slightly darker than expected.', 1),
(20, 'Priya', 'Exactly as pictured; love it!', 5),
(21, 'Sofia', 'Paper had a minor crease.', 2),
(21, 'Akira', 'Satisfied with the purchase.', 3),
(22, 'Ava', 'Beautiful print and great quality.', 4),
(22, 'Sofia', 'Paper had a minor crease.', 2),
(23, 'Liam', 'Adds style to my living room.', 5),
(23, 'Mateo', 'Colors are vibrant; looks fantastic framed.', 5),
(23, 'Lucas', 'Colors are vibrant; looks fantastic framed.', 4),
(23, 'Noah', 'Wish it came with a frame.', 1),
(24, 'Liu', 'Paper had a minor crease.', 2),
(24, 'Priya', 'Colors slightly darker than expected.', 2),
(24, 'Ava', 'Adds style to my living room.', 4),
(24, 'Emma', 'Exactly as pictured; love it!', 5),
(24, 'Hassan', 'Colors are vibrant; looks fantastic framed.', 4),
(25, 'Sofia', 'Colors slightly darker than expected.', 1),
(25, 'John', 'Exactly as pictured; love it!', 4),
(26, 'Olivia', 'Satisfied with the purchase.', 3),
(26, 'Hassan', 'Wish it came with a frame.', 1),
(26, 'Maria', 'Paper had a minor crease.', 1),
(26, 'Ava', 'Looks nice; size is accurate.', 3),
(27, 'Olivia', 'Beautiful print and great quality.', 4),
(27, 'Emma', 'Colors slightly darker than expected.', 2),
(27, 'Emma', 'Beautiful print and great quality.', 4),
(27, 'Ava', 'Paper had a minor crease.', 2),
(28, 'Akira', 'Adds style to my living room.', 4),
(28, 'Lucas', 'Arrived quickly and well-packaged.', 5),
(28, 'Mateo', 'Beautiful print and great quality.', 4),
(29, 'Ava', 'Adds style to my living room.', 4),
(29, 'Lucas', 'Satisfied with the purchase.', 3),
(29, 'Priya', 'Colors are vibrant; looks fantastic framed.', 5),
(30, 'Priya', 'Looks nice; size is accurate.', 3),
(30, 'Sofia', 'Exactly as pictured; love it!', 5),
(30, 'Ava', 'Wish it came with a frame.', 2),
(30, 'Mateo', 'Looks nice; size is accurate.', 3),
(31, 'Ava', 'Beautiful print and great quality.', 4),
(31, 'Maria', 'Adds style to my living room.', 5),
(31, 'Maria', 'Adds style to my living room.', 4),
(32, 'Olivia', 'Arrived quickly and well-packaged.', 5),
(32, 'Emma', 'Adds style to my living room.', 5),
(33, 'John', 'Colors are vibrant; looks fantastic framed.', 4),
(33, 'Olivia', 'Wish it came with a frame.', 1),
(34, 'Olivia', 'Arrived quickly and well-packaged.', 4),
(34, 'Sofia', 'Looks nice; size is accurate.', 3),
(34, 'Akira', 'Exactly as pictured; love it!', 4),
(34, 'Olivia', 'Arrived quickly and well-packaged.', 4),
(34, 'Hassan', 'Beautiful print and great quality.', 5),
(35, 'Mateo', 'Beautiful print and great quality.', 4),
(35, 'Akira', 'Satisfied with the purchase.', 3),
(35, 'Maria', 'Colors slightly darker than expected.', 1),
(36, 'Maria', 'Wish it came with a frame.', 2),
(36, 'Hassan', 'Satisfied with the purchase.', 3),
(36, 'Sofia', 'Satisfied with the purchase.', 3),
(37, 'Liu', 'Wish it came with a frame.', 1),
(37, 'John', 'Adds style to my living room.', 5),
(37, 'Elena', 'Colors are vibrant; looks fantastic framed.', 5),
(37, 'Olivia', 'Arrived quickly and well-packaged.', 5),
(37, 'Noah', 'Wish it came with a frame.', 1),
(38, 'Mateo', 'Colors are vibrant; looks fantastic framed.', 5),
(38, 'Sofia', 'Adds style to my living room.', 5),
(38, 'Ava', 'Colors slightly darker than expected.', 2),
(38, 'Mateo', 'Adds style to my living room.', 5),
(38, 'Sofia', 'Wish it came with a frame.', 2),
(39, 'Hassan', 'Wish it came with a frame.', 2),
(39, 'Olivia', 'Good quality for the price.', 3),
(39, 'Emma', 'Colors slightly darker than expected.', 2),
(39, 'Akira', 'Colors slightly darker than expected.', 1),
(40, 'Elena', 'Paper had a minor crease.', 1),
(40, 'Noah', 'Paper had a minor crease.', 1),
(40, 'Emma', 'Colors are vibrant; looks fantastic framed.', 5),
(41, 'Priya', 'Beautiful print and great quality.', 4),
(41, 'Sofia', 'Wish it came with a frame.', 1),
(41, 'Olivia', 'Looks nice; size is accurate.', 3),
(42, 'Priya', 'Exactly as pictured; love it!', 5),
(42, 'Priya', 'Colors are vibrant; looks fantastic framed.', 5),
(43, 'John', 'Beautiful print and great quality.', 4),
(43, 'Emma', 'Wish it came with a frame.', 1),
(44, 'Sofia', 'Colors slightly darker than expected.', 2),
(44, 'Sofia', 'Colors slightly darker than expected.', 1),
(44, 'Elena', 'Wish it came with a frame.', 2),
(44, 'Mateo', 'Colors slightly darker than expected.', 1),
(44, 'Priya', 'Paper had a minor crease.', 2),
(45, 'Hassan', 'Paper had a minor crease.', 1),
(45, 'Noah', 'Adds style to my living room.', 4),
(46, 'Sofia', 'Adds style to my living room.', 4),
(46, 'Maria', 'Satisfied with the purchase.', 3),
(46, 'Lucas', 'Colors slightly darker than expected.', 1),
(46, 'Noah', 'Paper had a minor crease.', 2),
(47, 'Noah', 'Good quality for the price.', 3),
(47, 'Akira', 'Beautiful print and great quality.', 5),
(47, 'Emma', 'Beautiful print and great quality.', 5),
(47, 'Olivia', 'Good quality for the price.', 3),
(48, 'Mateo', 'Colors are vibrant; looks fantastic framed.', 5),
(48, 'Mateo', 'Exactly as pictured; love it!', 5),
(48, 'Elena', 'Good quality for the price.', 3),
(48, 'Lucas', 'Paper had a minor crease.', 2),
(48, 'Olivia', 'Paper had a minor crease.', 2),
(49, 'Emma', 'Colors are vibrant; looks fantastic framed.', 4),
(49, 'Sofia', 'Colors are vibrant; looks fantastic framed.', 4),
(49, 'Emma', 'Paper had a minor crease.', 1),
(49, 'Liu', 'Good quality for the price.', 3),
(50, 'Priya', 'Satisfied with the purchase.', 3),
(50, 'Sofia', 'Paper had a minor crease.', 1),
(51, 'Sofia', 'Satisfied with the purchase.', 3),
(51, 'Mateo', 'Colors are vibrant; looks fantastic framed.', 4),
(51, 'John', 'Arrived quickly and well-packaged.', 5),
(51, 'Liu', 'Colors are vibrant; looks fantastic framed.', 5),
(52, 'Mateo', 'Beautiful print and great quality.', 4),
(52, 'Mateo', 'Colors slightly darker than expected.', 1),
(53, 'Liu', 'Looks nice; size is accurate.', 3),
(53, 'Maria', 'Colors are vibrant; looks fantastic framed.', 5),
(53, 'Maria', 'Beautiful print and great quality.', 4),
(54, 'Elena', 'Looks nice; size is accurate.', 3),
(54, 'Ava', 'Adds style to my living room.', 5),
(54, 'Ava', 'Adds style to my living room.', 4),
(54, 'Priya', 'Paper had a minor crease.', 1),
(55, 'Mateo', 'Beautiful print and great quality.', 5),
(55, 'Olivia', 'Colors are vibrant; looks fantastic framed.', 4),
(56, 'Akira', 'Arrived quickly and well-packaged.', 4),
(56, 'Mateo', 'Adds style to my living room.', 5),
(56, 'Noah', 'Paper had a minor crease.', 1),
(56, 'Elena', 'Adds style to my living room.', 4),
(56, 'Mateo', 'Exactly as pictured; love it!', 4),
(57, 'Elena', 'Arrived quickly and well-packaged.', 5),
(57, 'Ava', 'Looks nice; size is accurate.', 3),
(57, 'Maria', 'Good quality for the price.', 3),
(57, 'Mateo', 'Colors slightly darker than expected.', 2),
(58, 'Emma', 'Arrived quickly and well-packaged.', 4),
(58, 'Olivia', 'Paper had a minor crease.', 1),
(58, 'Maria', 'Adds style to my living room.', 4),
(59, 'Emma', 'Colors slightly darker than expected.', 1),
(59, 'Liam', 'Arrived quickly and well-packaged.', 4),
(59, 'Emma', 'Good quality for the price.', 3),
(59, 'Ava', 'Colors slightly darker than expected.', 1),
(60, 'Lucas', 'Colors slightly darker than expected.', 2),
(60, 'Liam', 'Beautiful print and great quality.', 5),
(60, 'Mateo', 'Paper had a minor crease.', 1),
(60, 'John', 'Colors are vibrant; looks fantastic framed.', 4),
(60, 'Hassan', 'Wish it came with a frame.', 1),
(61, 'Hassan', 'Paper had a minor crease.', 1),
(61, 'Priya', 'Paper had a minor crease.', 2),
(61, 'Mateo', 'Exactly as pictured; love it!', 4),
(62, 'Emma', 'Satisfied with the purchase.', 3),
(62, 'Lucas', 'Colors are vibrant; looks fantastic framed.', 5),
(62, 'Liam', 'Good quality for the price.', 3),
(62, 'Liu', 'Colors slightly darker than expected.', 2),
(62, 'Olivia', 'Exactly as pictured; love it!', 5),
(63, 'Elena', 'Satisfied with the purchase.', 3),
(63, 'Liam', 'Adds style to my living room.', 5),
(63, 'Priya', 'Paper had a minor crease.', 2),
(63, 'Sofia', 'Colors slightly darker than expected.', 2),
(64, 'Priya', 'Colors slightly darker than expected.', 1),
(64, 'Elena', 'Paper had a minor crease.', 1),
(64, 'Maria', 'Adds style to my living room.', 4),
(65, 'Sofia', 'Wish it came with a frame.', 1),
(65, 'John', 'Good quality for the price.', 3),
(66, 'Sofia', 'Exactly as pictured; love it!', 5),
(66, 'Liu', 'Exactly as pictured; love it!', 4),
(66, 'Hassan', 'Paper had a minor crease.', 2),
(67, 'Lucas', 'Colors slightly darker than expected.', 2),
(67, 'Liu', 'Wish it came with a frame.', 1),
(67, 'Liu', 'Paper had a minor crease.', 2),
(67, 'Noah', 'Good quality for the price.', 3),
(67, 'Akira', 'Satisfied with the purchase.', 3),
(68, 'Ava', 'Satisfied with the purchase.', 3),
(68, 'Noah', 'Wish it came with a frame.', 2),
(68, 'Mateo', 'Good quality for the price.', 3),
(68, 'Olivia', 'Exactly as pictured; love it!', 4),
(69, 'John', 'Arrived quickly and well-packaged.', 5),
(69, 'Mateo', 'Arrived quickly and well-packaged.', 5),
(70, 'Lucas', 'Good quality for the price.', 3),
(70, 'Elena', 'Colors slightly darker than expected.', 1),
(70, 'John', 'Exactly as pictured; love it!', 5),
(70, 'Liam', 'Exactly as pictured; love it!', 4),
(70, 'Olivia', 'Good quality for the price.', 3),
(71, 'Priya', 'Satisfied with the purchase.', 3),
(71, 'Hassan', 'Good quality for the price.', 3),
(71, 'Liam', 'Looks nice; size is accurate.', 3),
(72, 'Ava', 'Exactly as pictured; love it!', 4),
(72, 'Hassan', 'Colors are vibrant; looks fantastic framed.', 4),
(72, 'Olivia', 'Adds style to my living room.', 4),
(72, 'John', 'Paper had a minor crease.', 2),
(73, 'Hassan', 'Wish it came with a frame.', 1),
(73, 'Mateo', 'Arrived quickly and well-packaged.', 4),
(73, 'Liam', 'Wish it came with a frame.', 2),
(73, 'Emma', 'Looks nice; size is accurate.', 3),
(74, 'Mateo', 'Colors are vibrant; looks fantastic framed.', 5),
(74, 'John', 'Paper had a minor crease.', 2),
(74, 'Emma', 'Good quality for the price.', 3),
(75, 'Maria', 'Adds style to my living room.', 5),
(75, 'Mateo', 'Paper had a minor crease.', 2),
(75, 'Priya', 'Paper had a minor crease.', 1),
(76, 'Ava', 'Exactly as pictured; love it!', 5),
(76, 'John', 'Exactly as pictured; love it!', 5),
(77, 'Liam', 'Good quality for the price.', 3),
(77, 'John', 'Good quality for the price.', 3),
(78, 'Liam', 'Wish it came with a frame.', 1),
(78, 'Sofia', 'Colors are vibrant; looks fantastic framed.', 4),
(78, 'Emma', 'Adds style to my living room.', 4),
(79, 'Noah', 'Exactly as pictured; love it!', 4),
(79, 'Emma', 'Looks nice; size is accurate.', 3),
(79, 'Liu', 'Paper had a minor crease.', 2),
(79, 'Emma', 'Beautiful print and great quality.', 5),
(80, 'Emma', 'Exactly as pictured; love it!', 4),
(80, 'Emma', 'Paper had a minor crease.', 1),
(81, 'Ava', 'Beautiful print and great quality.', 4),
(81, 'Hassan', 'Beautiful print and great quality.', 5),
(82, 'Olivia', 'Arrived quickly and well-packaged.', 4),
(82, 'Sofia', 'Wish it came with a frame.', 2),
(83, 'Priya', 'Colors are vibrant; looks fantastic framed.', 4),
(83, 'Sofia', 'Looks nice; size is accurate.', 3),
(83, 'Ava', 'Exactly as pictured; love it!', 4),
(84, 'Liu', 'Paper had a minor crease.', 1),
(84, 'Elena', 'Wish it came with a frame.', 1),
(84, 'Emma', 'Colors slightly darker than expected.', 2),
(84, 'Emma', 'Paper had a minor crease.', 1),
(85, 'Liu', 'Beautiful print and great quality.', 5),
(85, 'John', 'Good quality for the price.', 3),
(86, 'Sofia', 'Satisfied with the purchase.', 3),
(86, 'Mateo', 'Wish it came with a frame.', 2),
(86, 'Mateo', 'Adds style to my living room.', 4),
(87, 'Akira', 'Exactly as pictured; love it!', 4),
(87, 'Akira', 'Exactly as pictured; love it!', 4),
(87, 'Lucas', 'Adds style to my living room.', 5),
(88, 'Liu', 'Looks nice; size is accurate.', 3),
(88, 'Priya', 'Satisfied with the purchase.', 3),
(88, 'Liu', 'Colors slightly darker than expected.', 1),
(88, 'Maria', 'Colors are vibrant; looks fantastic framed.', 4),
(88, 'Emma', 'Paper had a minor crease.', 2),
(89, 'Priya', 'Colors slightly darker than expected.', 1),
(89, 'Lucas', 'Paper had a minor crease.', 1),
(89, 'Liu', 'Good quality for the price.', 3),
(89, 'Mateo', 'Colors are vibrant; looks fantastic framed.', 4),
(90, 'Emma', 'Paper had a minor crease.', 2),
(90, 'Elena', 'Wish it came with a frame.', 2),
(90, 'Priya', 'Wish it came with a frame.', 2),
(90, 'Elena', 'Adds style to my living room.', 5),
(90, 'Maria', 'Colors are vibrant; looks fantastic framed.', 5),
(91, 'Sofia', 'Colors slightly darker than expected.', 1),
(91, 'John', 'Paper had a minor crease.', 2),
(91, 'Mateo', 'Satisfied with the purchase.', 3),
(92, 'Liam', 'Arrived quickly and well-packaged.', 4),
(92, 'Liam', 'Wish it came with a frame.', 1),
(93, 'Emma', 'Colors slightly darker than expected.', 1),
(93, 'Sofia', 'Beautiful print and great quality.', 4),
(93, 'Sofia', 'Beautiful print and great quality.', 4),
(93, 'Noah', 'Adds style to my living room.', 5),
(94, 'Lucas', 'Paper had a minor crease.', 2),
(94, 'Elena', 'Looks nice; size is accurate.', 3),
(94, 'Ava', 'Paper had a minor crease.', 1),
(94, 'Priya', 'Beautiful print and great quality.', 4),
(94, 'John', 'Satisfied with the purchase.', 3),
(95, 'Priya', 'Paper had a minor crease.', 1),
(95, 'Liam', 'Beautiful print and great quality.', 4),
(95, 'Maria', 'Arrived quickly and well-packaged.', 4),
(96, 'Elena', 'Wish it came with a frame.', 2),
(96, 'Liu', 'Colors slightly darker than expected.', 1),
(96, 'Olivia', 'Wish it came with a frame.', 2),
(96, 'Elena', 'Wish it came with a frame.', 2),
(96, 'Olivia', 'Adds style to my living room.', 4),
(97, 'Emma', 'Looks nice; size is accurate.', 3),
(97, 'Priya', 'Beautiful print and great quality.', 5),
(97, 'Sofia', 'Good quality for the price.', 3),
(97, 'Liam', 'Beautiful print and great quality.', 4),
(98, 'Elena', 'Satisfied with the purchase.', 3),
(98, 'Liam', 'Exactly as pictured; love it!', 4),
(98, 'Lucas', 'Arrived quickly and well-packaged.', 4),
(98, 'John', 'Colors slightly darker than expected.', 1),
(99, 'Priya', 'Wish it came with a frame.', 2),
(99, 'Akira', 'Colors slightly darker than expected.', 2),
(100, 'Lucas', 'Paper had a minor crease.', 1),
(100, 'Liam', 'Beautiful print and great quality.', 5),
(100, 'Sofia', 'Colors slightly darker than expected.', 1),
(100, 'John', 'Paper had a minor crease.', 2),
(100, 'Emma', 'Beautiful print and great quality.', 4);
